# Generated by Django 2.2 on 2020-11-17 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_reg_app', '0002_auto_20201116_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pitch', models.CharField(max_length=40)),
                ('about', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=25)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developed_by', to='login_reg_app.Dev')),
                ('watchers', models.ManyToManyField(related_name='watched_by', to='login_reg_app.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/project_pics')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project_pic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_pics', to='main_app.Project')),
            ],
        ),
    ]
