# Generated by Django 2.2.4 on 2020-11-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='times_viewed',
            field=models.IntegerField(default=0),
        ),
    ]
