# Generated by Django 2.2.4 on 2020-11-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_project_times_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='times_viewed',
            field=models.IntegerField(),
        ),
    ]
