# Generated by Django 2.2.4 on 2020-11-19 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0004_auto_20201118_1849'),
        ('main_app', '0004_auto_20201118_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='replier',
        ),
        migrations.AddField(
            model_name='reply',
            name='client_replier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_replies', to='login_reg_app.Client'),
        ),
        migrations.AddField(
            model_name='reply',
            name='dev_replier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dev_replies', to='login_reg_app.Dev'),
        ),
    ]
