# Generated by Django 2.2.4 on 2020-11-19 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20201118_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_image',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='project_image',
            name='project_pic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main_app.Project'),
        ),
    ]
