# Generated by Django 2.2.4 on 2020-11-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0002_auto_20201116_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dev',
            name='profile_pic',
            field=models.ImageField(default='/media/default.png', upload_to='media'),
        ),
    ]
