# Generated by Django 2.2.4 on 2020-11-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0006_auto_20201120_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dev',
            name='profile_pic',
            field=models.ImageField(default='media/default.png', upload_to='media'),
        ),
    ]
